#! /bin/bash

total_Mem =$ (free |grep Mem: |awk '{ print $2 }'| grep % | grep -v Use | sort -n |cut -d "%")

space=`df -h | awk '{print $5}' | grep % | grep -v Use | sort -n | tail -1 | cut -d "%" -f1 -`

echo "Enter critical threshold:"
read critical
 
echo "Enter warning threshold:"
read warning

echo "Enter Email address:"
read email


case $totalMem in
	1) $critical < $warning)
		echo "critical shoud be greater than warning threshold"
	;;
	
	2) [$critical = [3-5]*] && [$warning = [3-5]*]
		echo "$totalMem"
	;;

	3) [$critical = 1[1-9]] && [$warning = 1[1-9]]
		echo "$totalMem"
	;;

	4) [$warning = 2[1-9]] && [$warning = 2[1-9]]
		echo "$totalMem"
	;;
	
	5) [$critical = [6-7]*] && [$warning = [3-5]*]	
	
#----------------------------
	) [$critical = [2]] && $warning = [2]]
		echo "$totalMem %, is greater than or equal to crirical threshold "
	exit
	;;

	) [$critical = [1]] && [$warning = [1]]
		echo "$totalMem %, is greater than or equal to warning threshold but less than the crirtical threshold "
	exit
	;;
	
	) [$critical = [0]] && [$warning = [0]]
		echo "$totalMem %, is less than warning threshold "
	exit
	;;
esac

echo $totalMem | mail -s "Memory Usage Report `date`" $email

	

